version: "3.8"

services:
  web:
    image: kooldev/php:8.1-nginx
    volumes:
      - .:/app
    ports:
      - "8090:80"
    networks:
      - invoicing
  db:
    image: mysql:8.0
    restart: always
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: invoicing
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    volumes:
      - ./vendor/data/:/var/lib/mysql/
    networks:
      - invoicing

networks:
  invoicing:
